/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppUser {
  'favoriteStoryIds' : Array<bigint>,
  'languagePreference' : Language,
  'readingHistory' : Array<bigint>,
  'lastReadStoryId' : [] | [bigint],
  'readingChallengeProgress' : bigint,
  'searchHistory' : Array<string>,
  'dailyStreak' : bigint,
  'adsWatched' : bigint,
  'premiumSubscriptionActive' : boolean,
  'badgeAchievements' : Array<string>,
}
export interface Content {
  'title' : string,
  'body' : string,
  'summary' : string,
}
export type ExternalBlob = Uint8Array;
export type Language = { 'tamil' : null } |
  { 'hindi' : null } |
  { 'english' : null };
export interface Story {
  'id' : bigint,
  'isPremium' : boolean,
  'languages' : { 'tamil' : Content, 'hindi' : Content, 'english' : Content },
  'author' : string,
  'likes' : bigint,
  'coverImage' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'category' : string,
  'rating' : bigint,
  'isKidFriendly' : boolean,
  'readTimeMinutes' : bigint,
}
export interface UserProfile {
  'username' : string,
  'displayName' : string,
  'image' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAppUser' : ActorMethod<[], undefined>,
  'getAppUser' : ActorMethod<[], AppUser>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyFeaturedStoryByLanguage' : ActorMethod<[Language], Story>,
  'getFilteredSortedStories' : ActorMethod<
    [Language, [] | [boolean], [] | [string], [] | [boolean]],
    Array<Story>
  >,
  'getStory' : ActorMethod<[bigint], Story>,
  'getUserFavoriteStories' : ActorMethod<[], Array<Story>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishStory' : ActorMethod<
    [
      boolean,
      string,
      string,
      bigint,
      boolean,
      [] | [ExternalBlob],
      Content,
      Content,
      Content,
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleFavoriteStory' : ActorMethod<[bigint], undefined>,
  'updateAppUser' : ActorMethod<[AppUser], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];