/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Language = IDL.Variant({
  'tamil' : IDL.Null,
  'hindi' : IDL.Null,
  'english' : IDL.Null,
});
export const AppUser = IDL.Record({
  'favoriteStoryIds' : IDL.Vec(IDL.Nat),
  'languagePreference' : Language,
  'readingHistory' : IDL.Vec(IDL.Nat),
  'lastReadStoryId' : IDL.Opt(IDL.Nat),
  'readingChallengeProgress' : IDL.Nat,
  'searchHistory' : IDL.Vec(IDL.Text),
  'dailyStreak' : IDL.Nat,
  'adsWatched' : IDL.Nat,
  'premiumSubscriptionActive' : IDL.Bool,
  'badgeAchievements' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const Content = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'summary' : IDL.Text,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'isPremium' : IDL.Bool,
  'languages' : IDL.Record({
    'tamil' : Content,
    'hindi' : Content,
    'english' : Content,
  }),
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'coverImage' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'rating' : IDL.Nat,
  'isKidFriendly' : IDL.Bool,
  'readTimeMinutes' : IDL.Nat,
});
export const StoryDraft = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'authorRole' : IDL.Text,
  'isPrivate' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStoryDraft' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppUser' : IDL.Func([], [], []),
  'getAppUser' : IDL.Func([], [AppUser], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyFeaturedStoryByLanguage' : IDL.Func([Language], [Story], ['query']),
  'getFilteredSortedStories' : IDL.Func(
      [Language, IDL.Opt(IDL.Bool), IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
      [IDL.Vec(Story)],
      ['query'],
    ),
  'getMyStoryDrafts' : IDL.Func([], [IDL.Vec(StoryDraft)], ['query']),
  'getStory' : IDL.Func([IDL.Nat], [Story], ['query']),
  'getStoryDraft' : IDL.Func([IDL.Nat], [IDL.Opt(StoryDraft)], ['query']),
  'getUserFavoriteStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishStory' : IDL.Func(
      [
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
        Content,
        Content,
        Content,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFavoriteStory' : IDL.Func([IDL.Nat], [], []),
  'updateAppUser' : IDL.Func([AppUser], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Language = IDL.Variant({
    'tamil' : IDL.Null,
    'hindi' : IDL.Null,
    'english' : IDL.Null,
  });
  const AppUser = IDL.Record({
    'favoriteStoryIds' : IDL.Vec(IDL.Nat),
    'languagePreference' : Language,
    'readingHistory' : IDL.Vec(IDL.Nat),
    'lastReadStoryId' : IDL.Opt(IDL.Nat),
    'readingChallengeProgress' : IDL.Nat,
    'searchHistory' : IDL.Vec(IDL.Text),
    'dailyStreak' : IDL.Nat,
    'adsWatched' : IDL.Nat,
    'premiumSubscriptionActive' : IDL.Bool,
    'badgeAchievements' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Content = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'summary' : IDL.Text,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'isPremium' : IDL.Bool,
    'languages' : IDL.Record({
      'tamil' : Content,
      'hindi' : Content,
      'english' : Content,
    }),
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'coverImage' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'rating' : IDL.Nat,
    'isKidFriendly' : IDL.Bool,
    'readTimeMinutes' : IDL.Nat,
  });
  const StoryDraft = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'authorRole' : IDL.Text,
    'isPrivate' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStoryDraft' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppUser' : IDL.Func([], [], []),
    'getAppUser' : IDL.Func([], [AppUser], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyFeaturedStoryByLanguage' : IDL.Func(
        [Language],
        [Story],
        ['query'],
      ),
    'getFilteredSortedStories' : IDL.Func(
        [Language, IDL.Opt(IDL.Bool), IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getMyStoryDrafts' : IDL.Func([], [IDL.Vec(StoryDraft)], ['query']),
    'getStory' : IDL.Func([IDL.Nat], [Story], ['query']),
    'getStoryDraft' : IDL.Func([IDL.Nat], [IDL.Opt(StoryDraft)], ['query']),
    'getUserFavoriteStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishStory' : IDL.Func(
        [
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
          Content,
          Content,
          Content,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFavoriteStory' : IDL.Func([IDL.Nat], [], []),
    'updateAppUser' : IDL.Func([AppUser], [], []),
  });
};

export const init = ({ IDL }) => { return []; };